name: Deploy via FTPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Remove committed vendor (fresh install)
        run: |
          rm -rf vendor || true

      - name: Install Composer dependencies (if present)
        run: |
          if [ -f composer.json ]; then \
            composer install --no-dev --prefer-dist --optimize-autoloader; \
          else \
            echo "composer.json not found, skipping composer install"; \
          fi

      - name: Prepare root index upload
        run: |
          mkdir -p root-upload
          cp index.php root-upload/index.php

      - name: Deploy to Fasthosts via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: /htdocs/binday/
          local-dir: ./
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/storage/framework/cache/**/*
            **/storage/framework/sessions/**/*
            **/storage/framework/testing/**/*
            **/storage/logs/**/*
            **/tests/**
            **/.env
            **/.env.*
            **/database/*.sqlite
            **/deploy_ftp.ps1
            **/deploy/**
          dangerous-clean-slate: false

      - name: Upload root index.php to /htdocs
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: /htdocs/
          local-dir: ./root-upload/


